export const SITE = {
  name: "Slipyme Company",
  layoutTitle: "%s - Slipyme Company",
  legalName: "Slipyme Company",
  domain: "slipyme.com",
  url: "https://www.slipyme.com",
  titleTemplate: "%s - Slipyme Company",
  themeColor: "#2563eb",
  ogImage: "/resimler/logo.png",
  description:
    "Slipyme, çeşitli sektörlerde üst düzey hizmet sunma amacıyla kurulmuştur. Misyonumuz, faaliyet gösterdiğimiz sektörleri birbirleriyle entegre ederek kaliteli çözümler ortaya koymaktır. Şu anda, yazılım, tasarım ve oyun sektörlerinde etkinlik göstermekteyiz. Yazılım alanında, mobil, masaüstü, web tabanlı, website, gömülü, elektronik ve Arduino gibi geniş bir yelpazede projeler gerçekleştiriyoruz.",
  keywords: [
    "Slipyme Company",
    "Slipyme şirketi",
    "slipy",
    "slipybey",
    "slipbey",
    "slipyme",
    "enderrise",
    "blog",
    "react",
    "next",
    "reactjs",
    "nextjs",
    "tailwind",
    "tailwindcss",
    "software",
    "yazilim",
    "web",
    "programming",
    "css",
    "js",
    "nodejs",
    "mobil uygulama geliştirme",
    "masaüstü uygulama geliştirme",
    "web tabanlı uygulama geliştirme",
    "website tasarımı",
    "gömülü sistemler",
    "elektronik projeler",
    "Arduino projeleri",
    "oyun geliştirme",
    "kaliteli hizmet",
    "çözüm odaklı",
    "teknoloji",
    "yazılım çözümleri",
    "tasarım hizmetleri",
    "entegre çözümler",
    "üst düzey hizmet",
    "sektör entegrasyonu",
  ],
  emails: {
    contact: "contact@slipyme.com",
    media: "media@slipyme.com",
    jobs: "jobs@slipyme.com",
  },
} as const;

export type SiteConfig = typeof SITE;
