export const MEDIA_DATA = [
  {
    key: "logos",
    photos: [
      "/resimler/logo.png",
      "/resimler/pengu-emoji.png",
      "/resimler/penguen-emoji-siyah.png",
      "/resimler/slipyme-yazi.png",
      "/resimler/slipyme-yazi-siyah.png",
      "/resimler/logolar/botlist.png",
      "/resimler/logolar/code.png",
      "/resimler/logolar/design.png",
      "/resimler/logolar/logo_beyaz.png",
      "/resimler/logolar/logo_siyah.png",
      "/resimler/logolar/metal_penguen.png",
      "/resimler/logolar/penguen.jpg",
      "/resimler/logolar/penguen_beyaz.png",
      "/resimler/logolar/penguen_seffaf.png",
      "/resimler/logolar/penguenfesli.png",
      "/resimler/logolar/pengeun-altin.png",
      "/resimler/logolar/penguenyilbasi.png",
      "/resimler/logolar/todolist.png",
      "/resimler/logolar/yeni_penguen.png",
      "/resimler/logolar/testlogo.png",
    ],
  },
  {
    key: "banners",
    photos: [
      "/resimler/bannerlar/arka_banner.png",
      "/resimler/bannerlar/banner.png",
      "/resimler/bannerlar/discord_banner.png",
      "/resimler/bannerlar/logolar.png",
    ],
  },
  {
    key: "others",
    photos: [
      "/resimler/diger/arkaplan.png",
      "/resimler/diger/logo2.png",
      "/resimler/diger/tool_banner.png",
      "/resimler/diger/youtube_banner.png",
      "/resimler/diger/ytafis.png",
    ],
  },
  {
    key: "buildings",
    photos: [
      "/resimler/mockups/gar_bilboard.png",
      "/resimler/mockups/giriş.png",
      "/resimler/mockups/kariyer.png",
      "/resimler/mockups/örnek.jpg",
      "/resimler/mockups/örnek2.png",
      "/resimler/mockups/pano.png",
      "/resimler/mockups/reklam_afisi.png",
      "/resimler/mockups/reklam_bilboard.png",
      "/resimler/mockups/slipyme_bina.png",
      "/resimler/mockups/slipyme_cevre_duvar.png",
      "/resimler/mockups/slipyme_flama.png",
      "/resimler/mockups/slipyme_sirket.png",
      "/resimler/mockups/slipyme_tabela.png",
      "/resimler/mockups/sokak_panosu.png",
      "/resimler/mockups/pano2.png",
    ],
  },
  {
    key: "mockups",
    photos: [
      "/resimler/mockups/esofman.png",
      "/resimler/mockups/grisapka.png",
      "/resimler/mockups/onluk.png",
      "/resimler/mockups/sapka.png",
      "/resimler/mockups/slipyme_bardak.png",
      "/resimler/mockups/slipyme_corap.png",
      "/resimler/mockups/slipyme_tisort.png",
      "/resimler/mockups/slipyme_tisort_2.png",
      "/resimler/mockups/spgrisapka.png",
      "/resimler/mockups/spsapka.png",
      "/resimler/mockups/tisort.png",
      "/resimler/mockups/esofman2.png",
    ],
  },
] as const;
